/**
 * Agent Data & Microapps panel.
 *
 * Visualizes persistent structured records generated by agents and routines:
 *   - Categorized data cards (reports, metrics, microapp state)
 *   - Agent and category filtering
 *   - Formatted JSON inspector
 *   - Manual upsert / edit form for operator testing
 *   - Deletion
 */

import { useEffect, useState, type CSSProperties, type FormEvent } from 'react';
import { UI_LOCALE } from '../lib/numbers.js';
import { AnimatePresence, motion } from 'framer-motion';
import { Icon } from './ui/icons.js';
import { api, type AgentDataRow } from '../lib/transport.js';
import { useCortex } from '../store.js';
import { CortexEmpty, CortexPanel, Field, collapseMotion } from './CortexKit.js';

export function DataPanel({ onClose }: { onClose: () => void }) {
  const agents = useCortex((s) => s.agents);

  const [dataList, setDataList] = useState<AgentDataRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Filters
  const [filterAgent, setFilterAgent] = useState<string>('');
  const [filterCategory, setFilterCategory] = useState<string>('');

  // Expanded card IDs for JSON viewer
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  // Add/Edit Form state
  const [showAddForm, setShowAddForm] = useState(false);
  const [formAgentId, setFormAgentId] = useState(agents[0]?.id ?? '');
  const [formCategory, setFormCategory] = useState('general');
  const [formKey, setFormKey] = useState('');
  const [formDataJson, setFormDataJson] = useState('{\n  "status": "ok"\n}');
  const [saving, setSaving] = useState(false);

  const loadData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.agentData(filterAgent || undefined, filterCategory || undefined);
      setDataList(res.data);
    } catch (err: any) {
      setError(`Failed to load data: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadData();
  }, [filterAgent, filterCategory]);

  const toggleExpand = (id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const handleDelete = async (id: string, key: string) => {
    if (!confirm(`Delete record "${key}"?`)) return;
    try {
      await api.deleteAgentData(id);
      setDataList((list) => list.filter((item) => item.id !== id));
    } catch (err: any) {
      setError(`Failed to delete "${key}": ${err.message}`);
    }
  };

  const handleSaveData = async (e: FormEvent) => {
    e.preventDefault();
    if (!formKey.trim()) {
      setError('Key is required.');
      return;
    }
    const targetAgent = formAgentId || agents[0]?.id;
    if (!targetAgent) {
      setError('No bot selected.');
      return;
    }

    let parsedData: unknown;
    try {
      parsedData = JSON.parse(formDataJson);
    } catch (err: any) {
      setError(`Invalid JSON: ${err.message}`);
      return;
    }

    setSaving(true);
    setError(null);
    try {
      await api.setAgentData({
        agentId: targetAgent,
        key: formKey.trim(),
        category: formCategory.trim() || 'general',
        data: parsedData,
      });
      setFormKey('');
      setShowAddForm(false);
      await loadData();
    } catch (err: any) {
      setError(`Save failed: ${err.message}`);
    } finally {
      setSaving(false);
    }
  };

  // Extract unique categories for filter dropdown
  const categories = Array.from(new Set(dataList.map((d) => d.category))).sort();
  const agentName = (id: string) => agents.find((a) => a.id === id)?.name ?? id;

  return (
    <CortexPanel
      icon="data"
      title="Agent data"
      subtitle={loading ? 'Loading records…' : `${dataList.length} record${dataList.length === 1 ? '' : 's'}`}
      onClose={onClose}
      actions={
        <>
          <button
            type="button"
            className={`cx-icon-btn ${showAddForm ? 'is-on' : ''}`}
            aria-pressed={showAddForm}
            aria-label="Store a record"
            title="Store a record"
            onClick={() => setShowAddForm((v) => !v)}
          >
            <Icon name="add" />
          </button>
          <button type="button" className="cx-icon-btn" aria-label="Refresh data" title="Refresh" onClick={() => void loadData()}>
            <Icon name="refresh" />
          </button>
        </>
      }
    >
      <div className="cx-panel-toolbar cx-filters">
        <label className="cx-select-wrap">
          <Icon name="bot" size={14} motion={false} />
          <span className="cx-sr">Filter by bot</span>
          <select className="cx-select" value={filterAgent} onChange={(e) => setFilterAgent(e.target.value)}>
            <option value="">All bots</option>
            {agents.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name || a.id}
              </option>
            ))}
          </select>
        </label>
        <label className="cx-select-wrap">
          <Icon name="section" size={14} motion={false} />
          <span className="cx-sr">Filter by category</span>
          <select className="cx-select" value={filterCategory} onChange={(e) => setFilterCategory(e.target.value)}>
            <option value="">All categories</option>
            {categories.map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
        </label>
      </div>

      {error && (
        <div className="cx-alert" role="alert">
          <Icon name="error" size={14} motion={false} />
          <span>{error}</span>
        </div>
      )}

      <div className="cx-panel-body cx-stack">
        <AnimatePresence initial={false}>
          {showAddForm && (
            <motion.div key="form" className="cx-collapse" {...collapseMotion}>
              <form className="cx-form" onSubmit={handleSaveData}>
                <div className="cx-form-title">
                  <Icon name="data" size={14} motion={false} />
                  Store or update a record
                </div>
                <Field label="Bot">
                  <select className="cx-select" value={formAgentId || agents[0]?.id || ''} onChange={(e) => setFormAgentId(e.target.value)}>
                    {agents.map((a) => (
                      <option key={a.id} value={a.id}>
                        {a.name || a.id}
                      </option>
                    ))}
                  </select>
                </Field>
                <Field label="Category">
                  <input
                    type="text"
                    className="cx-input"
                    placeholder="general, report, metric…"
                    value={formCategory}
                    onChange={(e) => setFormCategory(e.target.value)}
                  />
                </Field>
                <Field label="Key" wide>
                  <input
                    type="text"
                    className="cx-input"
                    placeholder="daily-summary"
                    value={formKey}
                    onChange={(e) => setFormKey(e.target.value)}
                    required
                  />
                </Field>
                <Field label="JSON data" wide>
                  <textarea
                    className="cx-textarea is-code"
                    rows={5}
                    value={formDataJson}
                    onChange={(e) => setFormDataJson(e.target.value)}
                    required
                  />
                </Field>
                <div className="cx-form-actions">
                  <button type="button" className="cx-btn ghost" onClick={() => setShowAddForm(false)}>
                    Cancel
                  </button>
                  <button type="submit" className="cx-btn primary" disabled={saving}>
                    {saving ? 'Saving…' : 'Save record'}
                  </button>
                </div>
              </form>
            </motion.div>
          )}
        </AnimatePresence>

        {loading ? (
          <div className="cx-loading">
            <span className="cx-spinner" aria-hidden="true" />
            Loading records…
          </div>
        ) : dataList.length === 0 ? (
          <CortexEmpty icon="data" title="No records">
            Bots and scheduled routines store their reports and state here.
          </CortexEmpty>
        ) : (
          dataList.map((d, index) => {
            const isExpanded = expandedIds.has(d.id);
            let formattedJson = d.data_json;
            try {
              formattedJson = JSON.stringify(JSON.parse(d.data_json), null, 2);
            } catch {
              /* show the raw text */
            }

            return (
              <article key={d.id} className="cx-card cx-record" style={{ '--i': Math.min(index, 12) } as CSSProperties}>
                <div className="cx-row-between">
                  <div className="cx-record-title">
                    <span className="cx-record-key">{d.key}</span>
                    <span className="cx-chip">{d.category}</span>
                  </div>
                  <time className="cx-record-time">
                    {new Date(d.updated_at).toLocaleTimeString(UI_LOCALE, { hour: '2-digit', minute: '2-digit' })}
                  </time>
                </div>
                <p className="cx-record-meta">
                  {agentName(d.agent_id)}
                  {d.routine_id && (
                    <>
                      {' · routine '}
                      <code>{d.routine_id}</code>
                    </>
                  )}
                  {d.task_run_id && (
                    <>
                      {' · run '}
                      <code>{d.task_run_id}</code>
                    </>
                  )}
                </p>
                <div className="cx-actions-row">
                  <button type="button" className="cx-btn ghost" aria-expanded={isExpanded} onClick={() => toggleExpand(d.id)}>
                    <Icon name="chevronDown" size={13} className="cx-expand-chevron" motion={false} />
                    {isExpanded ? 'Hide data' : 'Show data'}
                  </button>
                  <button
                    type="button"
                    className="cx-icon-btn danger"
                    aria-label={`Delete ${d.key}`}
                    title="Delete record"
                    onClick={() => void handleDelete(d.id, d.key)}
                  >
                    <Icon name="remove" />
                  </button>
                </div>
                <AnimatePresence initial={false}>
                  {isExpanded && (
                    <motion.div key="json" className="cx-collapse" {...collapseMotion}>
                      <div className="cx-code">
                        <div className="cx-code-head">
                          <Icon name="data" size={13} motion={false} />
                          <span>{d.key}.json</span>
                        </div>
                        <pre>{formattedJson}</pre>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </article>
            );
          })
        )}
      </div>
    </CortexPanel>
  );
}
