import {useEffect,useState} from 'react';
import {getJson,postJson} from '../lib/transport.js';
import {RoutineAttention} from './RoutineAttention.js';
import {Plus, Trash2, LockKeyhole, CheckCheck, FileText, MessageCircle, Send, CircleHelp} from 'lucide-react';
import './BotWorkspace.css';
type Requirement={id:string;kind:'artifact'|'message'|'publication'|'custom';description:string;required:boolean;target:string;acceptance:{receipt:string;contains:string[];verifier:string;attachmentPaths?:string[]};dependencies:string[]};
export function ExpectedResults({agentId,routineId}:{agentId:string;routineId:string}){
  const [items,setItems]=useState<Requirement[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
  useEffect(()=>{const c=new AbortController();setLoaded(false);setItems([]);setError('');setSaved(false);getJson<{requirements:Requirement[]}>(`/api/system/expected-results?agent=${encodeURIComponent(agentId)}&routine=${encodeURIComponent(routineId)}`,c.signal).then(r=>{if(!c.signal.aborted){if(!Array.isArray(r.requirements)){setError('Expected results could not be loaded.');return;}setItems(r.requirements);setLoaded(true);}},()=>{if(!c.signal.aborted)setError('Expected results could not be loaded.');});return()=>c.abort();},[agentId,routineId]);
  const update=(id:string,patch:Partial<Requirement>)=>{setSaved(false);setItems(v=>v.map(r=>r.id===id?{...r,...patch}:r));};
  async function save(){setBusy(true);setError('');try{const result=await postJson<{requirements:Requirement[]}>('/api/system/expected-results',{agentId,routineId,requirements:items});if(!Array.isArray(result.requirements))throw new Error('The saved results could not be confirmed.');setItems(result.requirements);setSaved(true);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <section className="oh-expected-results" aria-label="Expected results"><RoutineAttention agentId={agentId} routineId={routineId}/><div className="oh-section-heading"><span className="oh-studio-eyebrow">Define done</span><h3>Expected results</h3><p>Choose what a successful run should produce. Completion needs matching evidence.</p></div>
    {!loaded&&!error&&<p role="status" className="grok-field-hint">Loading expected results…</p>}
    {loaded&&items.length===0&&<div className="oh-results-empty"><CheckCheck size={22}/><strong>Give success a clear definition</strong><p>Add a file, message or another result to check after each run.</p></div>}
    {items.map((r,index)=>{const ResultIcon={artifact:FileText,message:MessageCircle,publication:Send,custom:CircleHelp}[r.kind];return <fieldset className="oh-result-card" key={r.id} disabled={busy||r.id==='legacy-publication'}><legend><ResultIcon size={15}/>Result {String(index+1).padStart(2,'0')}{r.id==='legacy-publication'&&<span><LockKeyhole size={12}/>Linked requirement</span>}</legend><label className="oh-result-field">Result type<select value={r.kind} onChange={e=>{const kind=e.target.value as Requirement['kind'];update(r.id,{kind,acceptance:{receipt:kind==='artifact'?'created':kind==='publication'?'published':kind==='message'?'sent':'custom',contains:[],verifier:kind==='artifact'?'artifact/1':kind==='publication'?'stage1/1':kind==='message'?'whatsapp/1':'unconfigured'}});}}><option value="artifact">File or report</option><option value="message">Message</option><option value="publication">Publication</option><option value="custom">Other result</option></select></label>
      <label className="oh-result-field">Expected result<input placeholder="What should this run accomplish?" value={r.description} onChange={e=>update(r.id,{description:e.target.value})}/></label><label className="oh-result-field">Destination or file path<input placeholder={r.kind==='artifact'?'reports/weekly-summary.html':r.kind==='message'?'+966…':'Destination URL or result target'} value={r.target} onChange={e=>update(r.id,{target:e.target.value})}/></label>
      <label className="oh-result-required"><input type="checkbox" checked={r.required} onChange={e=>update(r.id,{required:e.target.checked})}/>Required for completion</label>
      {r.kind==='message'&&<label className="oh-result-field">Required receipt<select value={r.acceptance.receipt} onChange={e=>update(r.id,{acceptance:{...r.acceptance,receipt:e.target.value}})}><option value="sent">Sent</option><option value="delivered">Delivered</option></select></label>}
      {r.kind==='message'&&<label className="oh-result-field">Report attachment <small>Optional file path</small><input value={r.acceptance.attachmentPaths?.[0]??''} placeholder="report.html" onChange={e=>update(r.id,{acceptance:{...r.acceptance,attachmentPaths:e.target.value?[e.target.value]:[]}})}/></label>}
      <div className="oh-result-evidence"><CheckCheck size={15}/><p>{r.id==='legacy-publication'?'Linked to the existing publication requirement above.':r.kind==='artifact'?'Checked against the retained file.':r.kind==='message'?'Requires a matching message receipt.':r.kind==='publication'?'Requires a matching publication receipt.':'Needs a supported verifier before it can be confirmed.'} Without matching evidence, this stays unverified.</p></div>
      <details className="oh-result-technical"><summary>Verification details</summary><code>{r.acceptance.verifier}</code></details>
      {r.id!=='legacy-publication'&&<button type="button" className="oh-result-remove" onClick={()=>{setItems(v=>v.filter(i=>i.id!==r.id));setSaved(false);}}><Trash2 size={13}/>Remove result</button>}</fieldset>;})}
    <div className="oh-result-actions"><button type="button" disabled={!loaded||busy||items.length>=20} onClick={()=>{setSaved(false);setItems(v=>[...v,{id:crypto.randomUUID(),kind:'artifact',description:'',required:true,target:'',acceptance:{receipt:'created',contains:[],verifier:'artifact/1'},dependencies:[]}]);}}><Plus size={15}/>Add expected result</button>
    <button type="button" className="oh-results-save" disabled={!loaded||busy} onClick={()=>void save()}>{busy?'Saving…':'Save expected results'}</button></div>{saved&&<p role="status">Expected results saved for future runs.</p>}{error&&<p role="alert">{error}</p>}
  </section>;
}
